source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate-v2"
  gem "jekyll-auto-authors"
end

gem "minima", github: "jekyll/minima"
gem "webrick"